on: push
name: pythonworkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 2: Checkout code from repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Clean Data
      - name: Clean Data
        run: |
          python ModelCleaning/Cleandata.py

      # Step 5: Train and Test Model
      - name: Train and Test Model
        run: |
          python ModelCleaning/train_test_dataset.py